name: /home/hkinks
favicon: null
layout_spectrum: 0.29032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#464646'
    - '#f15a24'
    - '#f69470'
    - '#ffffff'
    - '#000000'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: c157671b-1482-41d3-90f7-bd9d05a84807
    url: null
